version: "3.3"

services:
  drone:
    image: drone/drone:2.12.1
    networks:
      - traefik_backend
    volumes:
      - data:/data
    environment:
      - DRONE_GITHUB_CLIENT_ID=$DRONE_GITHUB_CLIENT_ID
      - DRONE_GITHUB_CLIENT_SECRET=$DRONE_GITHUB_CLIENT_SECRET
      - DRONE_RPC_SECRET=$DRONE_RPC_SECRET
      - DRONE_SERVER_HOST=$DRONE_SERVER_HOST
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.drone.rule=Host(`$DRONE_SERVER_HOST`)"
      - "traefik.http.routers.drone.entrypoints=websecure"
      - "traefik.http.services.drone.loadbalancer.server.port=443"
      - "traefik.http.routers.drone.service=frontend"
      - "traefik.http.routers.drone.tls.certresolver=leresolver"


networks:
  traefik_backend:
    external: true

volumes:
  data:
